import type { SignedPart } from '@youandfriends/contracts';

import { UploadRequestError, type PartTransport, type UploadApi } from '../api';
import type { Hasher } from '../checksum';

/**
 * A scriptable upload server and bucket for the uploader's tests.
 *
 * The uploader's own logic — concurrency, retry, pause, resume — is what is under test here, so
 * the far side must be able to fail on command. The real endpoints are exercised end to end in
 * `lib/uploads/__tests__/routes.test.ts`.
 */
export const MIB = 1024 * 1024;

/** Generated bytes, never music (CLAUDE.md §8): a counter every 4 KiB tells slices apart. */
export function bytesOf(sizeBytes: number): Uint8Array<ArrayBuffer> {
  const bytes = new Uint8Array(sizeBytes);
  for (let index = 0; index < sizeBytes; index += 4096) bytes[index] = (index / 4096) % 256;
  return bytes;
}

export function fileOf(
  sizeBytes: number,
  name = 'Blue Hour.wav',
  lastModified = 1_700_000_000_000,
) {
  return new File([bytesOf(sizeBytes)], name, { type: 'audio/wav', lastModified });
}

export interface FakeServer {
  readonly api: UploadApi;
  readonly transport: PartTransport;
  readonly calls: { create: number; sign: number[][]; complete: number; abort: string[] };
  /** Part numbers PUT successfully, in arrival order (repeats included). */
  readonly put: number[];
  maxConcurrent: number;
  /** Fail the next N PUTs of this part with the given error. */
  failPart(partNumber: number, times: number, error: () => Error): void;
  /** Hold every PUT until `release()` is called. */
  hold(): void;
  release(): void;
  sessionPartSize: number;
}

export function fakeServer(): FakeServer {
  let counter = 0;
  let active = 0;
  let holding = false;
  let waiting: (() => void)[] = [];
  const failures = new Map<number, { times: number; error: () => Error }>();

  const server: FakeServer = {
    calls: { create: 0, sign: [], complete: 0, abort: [] },
    put: [],
    maxConcurrent: 0,
    sessionPartSize: 5 * MIB,
    failPart(partNumber, times, error) {
      failures.set(partNumber, { times, error });
    },
    hold() {
      holding = true;
    },
    release() {
      holding = false;
      const pending = waiting;
      waiting = [];
      for (const resolve of pending) resolve();
    },
    api: {
      async create(request) {
        server.calls.create += 1;
        counter += 1;
        return {
          id: `SESSION${counter}`,
          partSizeBytes: server.sessionPartSize,
          partCount: Math.ceil(request.sizeBytes / server.sessionPartSize),
          expiresAt: new Date(Date.now() + 86_400_000).toISOString(),
        };
      },
      async signParts(sessionId, partNumbers) {
        server.calls.sign.push([...partNumbers]);
        return partNumbers.map((partNumber): SignedPart => ({
          partNumber,
          url: `https://bucket.example/${sessionId}/${partNumber}?sig=secret`,
          expiresAt: new Date(Date.now() + 900_000).toISOString(),
        }));
      },
      async complete(_sessionId, request) {
        server.calls.complete += 1;
        return {
          created: true,
          sizeBytes: request.parts.reduce((sum, part) => sum + part.sizeBytes, 0),
          contentType: 'audio/wav',
          checksumSha256: null,
        };
      },
      async abort(sessionId) {
        server.calls.abort.push(sessionId);
      },
    },
    transport: async (url, body, onProgress, signal) => {
      const partNumber = Number(new URL(url).pathname.split('/').at(-1));
      active += 1;
      server.maxConcurrent = Math.max(server.maxConcurrent, active);
      try {
        // A real macrotask per part, so concurrent parts genuinely overlap.
        await new Promise((resolve) => setTimeout(resolve, 1));
        onProgress(Math.floor(body.size / 2));
        if (holding) {
          // An abort that already happened will never fire its event again.
          if (signal.aborted) throw new DOMException('Aborted', 'AbortError');
          await new Promise<void>((resolve, reject) => {
            waiting.push(resolve);
            signal.addEventListener(
              'abort',
              () => reject(new DOMException('Aborted', 'AbortError')),
              {
                once: true,
              },
            );
          });
        }
        if (signal.aborted) throw new DOMException('Aborted', 'AbortError');
        const failure = failures.get(partNumber);
        if (failure !== undefined && failure.times > 0) {
          failure.times -= 1;
          throw failure.error();
        }
        onProgress(body.size);
        server.put.push(partNumber);
        return { etag: `"etag-${partNumber}"` };
      } finally {
        active -= 1;
      }
    },
  };
  return server;
}

export const transient = () => new UploadRequestError('The network request failed.', 0, true);
export const refused = () => new UploadRequestError('Not found.', 404, false);

/** A hasher that reports progress and returns a fixed digest. The real one is tested alone. */
export const instantHasher: Hasher = async (file, onProgress) => {
  onProgress(file.size);
  return 'a'.repeat(64);
};

export const noSleep = async () => {};
