/**
 * Scratch space for a job, bounded and always cleaned up.
 *
 * A transcode needs somewhere to put an intermediate file. Two things go wrong with that, and
 * both go wrong quietly:
 *
 *   - **The directory outlives the job.** A worker that processes a thousand files and cleans up
 *     after nine hundred of them fills its disk in a week, and the failure surfaces as unrelated
 *     jobs failing to write. Cleanup here is in a `finally`, so it happens on the throw path too
 *     — which is the path that matters, because the jobs that leave debris are the ones that
 *     crashed.
 *   - **The output is larger than anyone expected.** ffmpeg asked for a pathological input can
 *     produce far more than it consumed.
 *
 * **What this is honest about:** `assertWithinBudget` is a *check*, not a quota. It measures what
 * has been written and refuses to continue past the limit; it cannot stop a single `write` from
 * filling the disk between two checks. A real bound is a filesystem quota or a container limit,
 * and that belongs to deployment rather than to this file. What this gives you is a job that
 * fails with a clear reason instead of a worker that wedges — and cleanup either way.
 */
import { mkdtemp, rm, readdir, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/** 2 GiB. A 5 GB original transcoding to AAC needs far less; this is the runaway case. */
export const DEFAULT_TEMP_BUDGET_BYTES = 2 * 1024 * 1024 * 1024;

export class TempBudgetExceededError extends Error {
  constructor(
    readonly usedBytes: number,
    readonly limitBytes: number,
  ) {
    super(`job scratch space reached ${usedBytes} bytes, over its ${limitBytes} byte budget`);
    this.name = 'TempBudgetExceededError';
  }
}

export interface TempWorkspace {
  readonly dir: string;
  /** Throws if what has been written so far exceeds the budget. Call between stages. */
  assertWithinBudget(): Promise<void>;
  usedBytes(): Promise<number>;
}

/**
 * Run `work` with a private temporary directory, removed afterwards no matter what.
 *
 * The random part of the name is generated by `mkdtemp`. The optional `prefix` **is** composed
 * into the path, and the result is later removed recursively — so it is validated to a
 * conservative character set here rather than trusted. A prefix containing `../` would otherwise
 * escape `tmpdir()` and take the `rm -rf` with it. The docstring used to claim no part of the
 * name came from a caller, which was not true of this argument (found in review).
 */
export async function withTempWorkspace<T>(
  work: (workspace: TempWorkspace) => Promise<T>,
  options: { readonly budgetBytes?: number; readonly prefix?: string } = {},
): Promise<T> {
  const limit = options.budgetBytes ?? DEFAULT_TEMP_BUDGET_BYTES;
  const prefix = options.prefix ?? 'youandfriends-audio-';
  // The character class alone is not enough: it admits `..`, and `join(tmpdir(), '..')` is `/`,
  // so `mkdtemp` would create — and this function would later recursively remove — a directory
  // at the filesystem root. Caught by the test for this guard, which is the point of writing it.
  if (!/^[A-Za-z0-9._-]+$/.test(prefix) || prefix.includes('..')) {
    throw new Error(
      `temp workspace prefix ${JSON.stringify(prefix)} may only contain letters, digits, dot, ` +
        'dash and underscore, and may not contain ".." — it becomes part of a path that is ' +
        'later removed recursively',
    );
  }
  const dir = await mkdtemp(join(tmpdir(), prefix));

  const usedBytes = () => directorySize(dir);

  const workspace: TempWorkspace = {
    dir,
    usedBytes,
    async assertWithinBudget() {
      const used = await usedBytes();
      if (used > limit) throw new TempBudgetExceededError(used, limit);
    },
  };

  try {
    return await work(workspace);
  } finally {
    // `force` so a job that already removed its own files does not fail here, and a failure to
    // clean up is never allowed to mask the original error.
    await rm(dir, { recursive: true, force: true }).catch(() => undefined);
  }
}

/** Bytes on disk under `dir`, following its subdirectories but never a symlink out of it. */
async function directorySize(dir: string): Promise<number> {
  let total = 0;
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      total += await directorySize(path);
    } else if (entry.isFile()) {
      // `stat` rather than `lstat` is deliberate for files but the symlink case is excluded
      // above by `isFile()`, which is false for a link — a link pointing at a 40 GB file must
      // not be counted as though the job had written one.
      total += (await stat(path)).size;
    }
  }

  return total;
}
